drop table Employee;
CREATE table Employee (
    employee_id INT NOT NULL,
    Ename VARCHAR(50) NOT NULL,
    department_id INT NOT NULL,
    salary DECIMAL(10, 2) NOT NULL,
    join_date DATE NOT NULL,
    manager_id INT,
    job_title VARCHAR(50) NOT NULL
);
INSERT INTO Employee (employee_id, Ename, department_id, salary, join_date, manager_id, job_title) VALUES
(1, 'Alice', 101, 75000, '2019-03-15', NULL, 'Manager'),
(2, 'Bob', 101, 65000, '2018-05-20', 1, 'Developer'),
(3, 'Charlie', 102, 85000, '2020-07-10', 1, 'Developer'),
(4, 'Diana', 102, 72000, '2021-02-05', 3, 'Analyst'),
(5, 'Eva', 103, 68000, '2017-12-12', NULL, 'Developer'),
(6, 'Frank', 103, 62000, '2019-06-01', 5, 'Tester'),
(7, 'Grace', 104, 90000, '2022-08-18', 1, 'Manager'),
(8, 'Henry', 104, 77000, '2019-11-10', 7, 'Analyst'),
(9, 'Ian', 105, 61000, '2020-01-20', NULL, 'Intern'),
(1, 'Alice', 102, 64000, '2022-01-15', 2, 'Developer'),
(2, 'Bob', 102, 70000, '2020-11-22', 1, 'Analyst'),
(6, 'Frank', 103, 88000, '2019-05-13', 3, 'Developer');
drop table department;
CREATE TABLE department (
    department_id INT  ,
    department_name VARCHAR(50)
);
INSERT INTO department (department_id, department_name) VALUES
(101, 'HR'),
(102, 'IT'),
(103, 'Sales'),
(104, 'Finance'),
(105, 'Marketing'),
(106, 'Admin'),
(107, 'Support');
drop table project;
CREATE TABLE project(
    project_id INT  ,
    employee_id INT,
    project_name VARCHAR(100)
);
INSERT INTO project (project_id, employee_id, project_name) VALUES 
(1, 1, 'Project Alpha'),
(2, 6, 'Project Beta'),
(3, 4, 'Project Gamma'),
(4, 9, 'Project Delta'),
(5, 5, 'Project Epsilon');
COMMIT;


#Ques_1 : find the avg salary group by department_name
SELECT DEPARTMENT_NAME,AVG(SALARY) AS AVG_SAL
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;
 
#Ques_2 :  get employee details who have the same department_id
SELECT E.EMPLOYEE_ID, E.ENAME, E.DEPARTMENT_ID, E.SALARY, E.JOIN_DATE, E.MANAGER_ID, E.JOB_TITLE
FROM EMPLOYEE E
JOIN EMPLOYEE A
ON E.DEPARTMENT_ID=A.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID<>A.EMPLOYEE_ID
ORDER BY DEPARTMENT_ID;

SELECT EMPLOYEE_ID ,ENAME, DEPARTMENT_ID, SALARY, JOIN_DATE, MANAGER_ID, JOB_TITLE
FROM EMPLOYEE
WHERE DEPARTMENT_ID IN
(SELECT DEPARTMENT_ID
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>1
)ORDER BY DEPARTMENT_ID;

WITH SAME_DEPT AS(
	SELECT *, COUNT(*) OVER (PARTITION BY DEPARTMENT_ID ) AS CNT
    FROM EMPLOYEE
)
SELECT EMPLOYEE_ID ,ENAME, DEPARTMENT_ID, SALARY, JOIN_DATE, MANAGER_ID, JOB_TITLE 
FROM SAME_DEPT
WHERE CNT>1;
 
#Ques_3 :  get employee details along with the manager name
SELECT E.EMPLOYEE_ID, E.ENAME, E.DEPARTMENT_ID, E.SALARY, E.JOIN_DATE, E.JOB_TITLE, E.MANAGER_ID, M.ENAME AS MANAGER_NAME
FROM EMPLOYEE E 
LEFT JOIN EMPLOYEE M
ON E.MANAGER_ID=M.EMPLOYEE_ID;

#Ques_4 :  Find all employees who haven’t worked on any project 
SELECT EMPLOYEE_ID,ENAME
FROM EMPLOYEE
WHERE EMPLOYEE_ID NOT IN
(
	SELECT EMPLOYEE_ID FROM PROJECT
);

#Ques_5 :  Find the most recent hire in each department
SELECT DEPARTMENT_NAME, EMPLOYEE_ID, ENAME
FROM (
	SELECT DEPARTMENT_NAME,EMPLOYEE_ID,ENAME,JOIN_DATE , MAX(JOIN_DATE) OVER(PARTITION BY DEPARTMENT_NAME) AS RECENT_JOINER
    FROM EMPLOYEE E
    JOIN  DEPARTMENT D
    ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
    )T
WHERE JOIN_DATE= RECENT_JOINER;

WITH RECENT_JOINER AS
(
	SELECT DEPARTMENT_NAME,ENAME,JOIN_DATE, ROW_NUMBER() OVER (PARTITION BY DEPARTMENT_NAME ORDER BY JOIN_DATE DESC) AS RECENT_DATE
    FROM EMPLOYEE E 
    JOIN DEPARTMENT D
    ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
)
SELECT DEPARTMENT_NAME, ENAME, JOIN_DATE
FROM RECENT_JOINER
WHERE RECENT_DATE=1;

#Ques_6 : find out the employee name and corresponding department name of the employee
SELECT ENAME, DEPARTMENT_NAME
FROM EMPLOYEE E 
JOIN DEPARTMENT D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY ENAME;

#Ques_7 : show the employee information in the order by salary in decreaing order
SELECT EMPLOYEE_ID, ENAME, DEPARTMENT_ID, SALARY, JOIN_DATE, MANAGER_ID, JOB_TITLE
FROM EMPLOYEE
ORDER BY SALARY DESC;

#Ques_8 : show the employee information in the order by salary in decreaing order deparment wise
SELECT E.EMPLOYEE_ID,
       E.ENAME,
       E.SALARY,
       E.JOIN_DATE,
       E.MANAGER_ID,
       E.JOB_TITLE,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_ID, E.SALARY DESC;

#Ques_9 : create a new column named as salary_category and write the logic in this way if salary is greate then 70000 then 'High' else 'Low' 	
SELECT EMPLOYEE_ID, ENAME, SALARY, 
	CASE 
		WHEN SALARY>70000 THEN 'HIGH'
        ELSE 'LOW'
	END AS SALARY_CATEGORY    
FROM EMPLOYEE;
        
#Ques_10 : find employee name who are the manager
SELECT DISTINCT EMPLOYEE_ID, ENAME
FROM EMPLOYEE
WHERE EMPLOYEE_ID IN (
	SELECT MANAGER_ID
    FROM EMPLOYEE
);

#Ques_11 : Find the sum of salaries for each department.
SELECT DEPARTMENT_NAME, SUM(SALARY) AS TOTAL_SALARY
FROM DEPARTMENT D 
JOIN EMPLOYEE E USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

#Ques_12 : Find the avg of salaries for each department
SELECT D.DEPARTMENT_NAME,AVG(SALARY) 
FROM EMPLOYEE E 
JOIN DEPARTMENT D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;

#Ques_13 : Find out the department name that has the more then one employee
SELECT DEPARTMENT_NAME
FROM
(
	SELECT D.DEPARTMENT_NAME, COUNT(*)
    FROM EMPLOYEE E 
    JOIN DEPARTMENT D
    ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_NAME
	HAVING COUNT(*)>1
)T;

SELECT D.DEPARTMENT_NAME
FROM EMPLOYEE E 
JOIN DEPARTMENT D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(*)>1;

#Ques_14 : Count the number of employees in each department
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(*) AS COUNTOFEMPLOYEES
FROM EMPLOYEE E 
JOIN DEPARTMENT D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, DEPARTMENT_NAME;

#Ques_15 : Find employees without a manager.
SELECT EMPLOYEE_ID, ENAME, DEPARTMENT_ID, SALARY, JOIN_DATE, MANAGER_ID, JOB_TITLE
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL;

#Ques_16 : Find employees who have more than one manager.
SELECT EMPLOYEE_ID, ENAME
FROM EMPLOYEE
GROUP BY EMPLOYEE_ID,ENAME
HAVING COUNT(DISTINCT MANAGER_ID)>1;

#Ques_17 : Find departments with no employees
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENT
WHERE DEPARTMENT_ID NOT IN(
SELECT DEPARTMENT_ID
FROM EMPLOYEE
);

#Ques_18 : Find average salary by department and order by highest average salary
SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SAL
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID
ORDER BY AVG_SAL DESC; 

#Ques_19 : Find the department with the highest number of employees.
WITH MAX_EMP_DEPT AS (
	SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) OVER (PARTITION BY E.DEPARTMENT_ID) AS CNT
    FROM EMPLOYEE E
    JOIN DEPARTMENT D
    ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
    ORDER BY CNT DESC) 
SELECT DISTINCT DEPARTMENT_ID, DEPARTMENT_NAME
FROM MAX_EMP_DEPT
    WHERE CNT IN (SELECT MAX(CNT) FROM MAX_emp_DEPT);

#Ques_20 : Find departments with less than 5 employees
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) AS TOTALEMP
FROM EMPLOYEE E 
JOIN DEPARTMENT D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY 1,2
HAVING TOTALEMP<5;

SELECT  DISTINCT DEPARTMENT_ID, DEPARTMENT_NAME
FROM
(
	SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, 
    COUNT(E.EMPLOYEE_ID) OVER(PARTITION BY DEPARTMENT_ID) AS CNT
    FROM EMPLOYEE E 
    JOIN DEPARTMENT D
    ON E.DEPARTMENT_ID=D.DEPARTMENT_ID)T
WHERE CNT<5;

#Ques_21 : Find employees who belong to multiple departments
SELECT EMPLOYEE_ID, ENAME
FROM EMPLOYEE
GROUP BY EMPLOYEE_ID, ENAME
HAVING COUNT(DISTINCT DEPARTMENT_ID) > 1;

WITH MUL_DEPT AS
(
	SELECT E.EMPLOYEE_ID, E.ENAME, E.DEPARTMENT_ID, COUNT(E.DEPARTMENT_ID) OVER (PARTITION BY E.EMPLOYEE_ID) AS CNT
    FROM EMPLOYEE E, EMPLOYEE D
    WHERE E.EMPLOYEE_ID=D.EMPLOYEE_ID
    AND E.DEPARTMENT_ID<>D.DEPARTMENT_ID
)
SELECT DISTINCT EMPLOYEE_ID, ENAME
FROM MUL_DEPT
WHERE CNT>1;

#Ques_22 : Find employees name who are not managers. by using sub query
SELECT ENAME
FROM EMPLOYEE
WHERE EMPLOYEE_ID NOT IN(SELECT MANAGER_ID FROM EMPLOYEE WHERE MANAGER_ID IS NOT NULL);

#WITH LEFT JOIN
SELECT E.ENAME
FROM EMPLOYEE E 
LEFT JOIN EMPLOYEE M
ON E.EMPLOYEE_ID= M.MANAGER_ID
WHERE M.MANAGER_ID IS NULL;

#Ques_23 : Find departments with fewer than 5 employees
SELECT D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM DEPARTMENT D
JOIN EMPLOYEE E 
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID,D.DEPARTMENT_NAME
HAVING COUNT(DISTINCT E.EMPLOYEE_ID)<5;

#Ques_24 : Find employees whose salary is more than average salary of their department.
SELECT EMPLOYEE_ID, ENAME, DEPARTMENT_ID
FROM(
	SELECT EMPLOYEE_ID, ENAME, SALARY, DEPARTMENT_ID, AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID) AS AVG_SAL
    FROM EMPLOYEE
)T;

#Ques_25 :  Find the departments with the highest  number of employees.
SELECT DISTINCT DEPARTMENT_ID, DEPARTMENT_NAME
FROM (
	SELECT DEPARTMENT_ID, DEPARTMENT_NAME, DENSE_RANK() OVER (ORDER BY CNT DESC) AS RNK
	FROM(
		SELECT D.DEPARTMENT_ID,D.DEPARTMENT_NAME,  COUNT(DISTINCT EMPLOYEE_ID) AS CNT
		FROM EMPLOYEE E
		JOIN DEPARTMENT D
		ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
        GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
        )T)T
WHERE RNK=1;

SELECT DISTINCT DEPARTMENT_ID, DEPARTMENT_NAME
FROM (
	SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, DENSE_RANK() OVER (ORDER BY COUNT(DISTINCT EMPLOYEE_ID) DESC) AS RNK
	FROM EMPLOYEE E
	JOIN DEPARTMENT D
	ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
	GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
        )T
WHERE RNK=1;

WITH HIGHEST_EMP AS (
	SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, DENSE_RANK() OVER (ORDER BY COUNT(DISTINCT E.EMPLOYEE_ID) DESC) AS RNK
	FROM EMPLOYEE E
	JOIN DEPARTMENT D
	ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM HIGHEST_EMP
WHERE RNK=1;


#Ques_26 :  Find the departments with the lowest  number of employees.
WITH LOWEST_EMP AS(
	SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME,DENSE_RANK() OVER(ORDER BY COUNT(DISTINCT E.EMPLOYEE_ID) ASC)    AS RNK
    FROM EMPLOYEE E 
    JOIN DEPARTMENT D
    ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
	)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM LOWEST_EMP
WHERE RNK=1;


#Ques_27 : Find employees who have a lower salary than their manager
WITH LOW_SAL AS(
	SELECT E.EMPLOYEE_ID, E.ENAME, E.SALARY AS EMPLOYEE_SAL, E.MANAGER_ID, M.SALARY AS MANAGER_SAL
    FROM EMPLOYEE E
    JOIN EMPLOYEE M
    ON E.MANAGER_ID=M.EMPLOYEE_ID
    WHERE E.SALARY<M.SALARY
)
SELECT DISTINCT EMPLOYEE_ID, ENAME
FROM LOW_SAL;


#Ques_28 : Find the name of employees who have worked in more than one department.
SELECT EMPLOYEE_ID, ENAME, COUNT(DISTINCT DEPARTMENT_ID) AS CNT
FROM EMPLOYEE
GROUP BY EMPLOYEE_ID, ENAME
HAVING COUNT(DISTINCT DEPARTMENT_ID)>1;


#Ques_29 : count the number of unique job titles.
SELECT COUNT(DISTINCT JOB_TITLE) AS JOB_TITLE_COUNT
FROM EMPLOYEE;


#Ques_30 : Find departments where employees have higher salaries than their managers.
WITH HIGH_SAL AS(
	SELECT E.DEPARTMENT_ID, E.EMPLOYEE_ID, E.SALARY AS EMP_SAL, E.MANAGER_ID, M.SALARY AS MANAGER_SAL
    FROM EMPLOYEE E 
    JOIN EMPLOYEE M
    ON E.MANAGER_ID=M.EMPLOYEE_ID
    WHERE E.SALARY>M.SALARY
)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENT
WHERE DEPARTMENT_ID IN 
(SELECT DISTINCT DEPARTMENT_ID FROM HIGH_SAL);